### ISSUE TITLE
example of converting to a NaiveDateTime from a microsecond instead of nanosecond

### ISSUE THREAD

**Issue by era127** [Swoorup/arrow-convert#7]
Hi, do you have an example of how you could convert a timestamp which is in microseconds (such as that returned by duckdb quary_arrow) to a NaiveDateTime.  The default for NaiveDateTime is currently an arrow nanosecond timestamp, but duckdb uses microseconds.  Thanks!

**Comment by Swoorup** [comment]
You'll probably need to create an ArrowField that serializes/deserializes to the correct arrow type supported by duckdb. 

See https://github.com/Swoorup/arrow-convert/blob/4ba848fe6a91f4f4e3f1aafdbc14c1a834f28e40/arrow_convert/src/field.rs#L169

You also want to use a Unit struct for the field and then have the associated type parameter point like chrono's datetime or something. And then you can then do like
```rust
#[arrow_field(type = "my_crate::DuckDbMicrosecond")
```
